### ISSUE TITLE
I cant set custom path for other button than A,B,X and Y in relaunch gui.

### ISSUE THREAD

**Issue by antoine62** [FlameKat53/Relaunch#21]
Please, add this! 
### Tank you ^_^

**Comment by FlameKat53** [comment]
I will eventually, thanks for your interest in Relaunch!

**Comment by FlameAlt53** [comment]
there it is, I hope it compiles and doesn't do any guru errors

**Comment by FlameKat53** [comment]
merged, atm it isnt testable as the filemenu is a bit broken, but i think Pk11 will fix it
